// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmfkloJfhwiWBaVL67JU9HqGZ1ADodNw',
    appId: '1:70390748137:web:4144881e4639880efaf178',
    messagingSenderId: '70390748137',
    projectId: 'bharita-a41fa',
    authDomain: 'bharita-a41fa.firebaseapp.com',
    databaseURL: 'https://bharita-a41fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharita-a41fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0g6u_gmgOK4gQsExiYBI79QUbdkhFwjc',
    appId: '1:70390748137:android:c5080135555f0c8bfaf178',
    messagingSenderId: '70390748137',
    projectId: 'bharita-a41fa',
    databaseURL: 'https://bharita-a41fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharita-a41fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvVhvyagQBreqKeYbGAQYaeGzCz6WUNE',
    appId: '1:70390748137:ios:74647ab480bc6764faf178',
    messagingSenderId: '70390748137',
    projectId: 'bharita-a41fa',
    databaseURL: 'https://bharita-a41fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharita-a41fa.firebasestorage.app',
    iosBundleId: 'com.example.brio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAvVhvyagQBreqKeYbGAQYaeGzCz6WUNE',
    appId: '1:70390748137:ios:74647ab480bc6764faf178',
    messagingSenderId: '70390748137',
    projectId: 'bharita-a41fa',
    databaseURL: 'https://bharita-a41fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharita-a41fa.firebasestorage.app',
    iosBundleId: 'com.example.brio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVmfkloJfhwiWBaVL67JU9HqGZ1ADodNw',
    appId: '1:70390748137:web:e2b80f9a62465fd3faf178',
    messagingSenderId: '70390748137',
    projectId: 'bharita-a41fa',
    authDomain: 'bharita-a41fa.firebaseapp.com',
    databaseURL: 'https://bharita-a41fa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bharita-a41fa.firebasestorage.app',
  );
}
